config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'post#index'
  
  get 'reply/create'
  post 'reply/create'

  get 'reply/destroy'
  get 'reply/destroy/:id' => 'reply#destroy'
  
  get 'post/index'

  get 'post/new'

  get 'post/create'
  post 'post/create' # 정보를 암호화해서 보내는데 rails가 token으로 막아놓았음

  get 'post/update'
  post 'post/update/:id' => 'post#update'

  get 'post/edit'
  get 'post/edit/:id' => 'post#edit'

  get 'post/destroy'
  get 'post/destroy/:id' => 'post#destroy'

  get 'post/show'
  get 'post/show/:id' => 'post#show'
  
  get 'post/search'

  get 'likes/likes_toggle/:id' => 'likes#likes_toggle'
  
  
  get 'post/ajaxCall' => 'post#ajaxCall' # 에이젝스 통신

end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :replies # 뒤에는 복수 형태가 옴
    belongs_to :user
    
    has_many :likes
    has_many :liked_users, through: :likes, source: :user
    
    validates :title, presence: true

end

app/models/reply.rb
class Reply < ActiveRecord::Base
    belongs_to :post # 하나에 종속되있기 때문에 단수를 씀
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
          
  has_many :posts
  has_many :replies
  has_many :likes
  has_many :liked_post, through: :likes, source: :post
          
  def is_like?(post) # 실제로 존재하는지 안하는지 찾을 수 있따.
      Like.find_by(user_id: self.id, post_id: post.id).present?
    #   자기 아이디 받아올 때는 self.id
    # post_id를 받아올 수 없어서 매게변수로 받아온다(post)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    # sign_up할 때 username을 열어준다.
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    
    def likes_toggle
        like = Like.find_by(user_id: current_user.id, post_id: params[:id])
        
        if like.nil?
            Like.create(user_id: current_user.id, post_id: params[:id])
            
            # 위에 코드랑 같은 코드
            # @likes = Like.new
            # @likes.user_id = current_user
            # @likes.post_id = params[:id]
            #@likes.save
        else
            like.destroy
        end
        redirect_to :back
    end
    
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  # before_action :authenticate_user! # 모든 action하기 전에 먼저 실행
  before_action :authenticate_user!, except: [:index, :show]
  # before_action :authenticate_user!, only: [:index, :new]

  def index
    @post = Post.all.reverse
  end

  def new #new action은 할일이 없음 그냥 화면(view)만 필요함
  # 로그인 여부 확인하기
  end

  def create
    uploader = ImageUploader.new # imageuploader를 uploader에 저장
    uploader.store!(params[:image]) # 들어온 file(image)을 저장

    @post = Post.new # model은 대문자로 시작
    
    @post.title = params[:input_title]
    @post.content = params[:input_content]
    @post.user_id = current_user.id #user_id 꼭 해야함
    @post.image = uploader.url
    # 데이터베이스를 삭제하지 않고 colum을 추가하는 방법
    # rails g migration add_변수명_to_적용시킬 데이터모델 변수명:자료형
    @post.thumb = uploader.thumb.url
    @post.middle = uploader.middle.url
    
    @post.save
    redirect_to "/post/index"
  end

  def update
    @post = Post.find(params[:id])
    
    @post.title = params[:input_title]
    @post.content = params[:input_content]
    
    @post.save
    redirect_to "/post/show/#{params[:id]}"
  end

  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    if current_user.id = @post.user_id
      @post.destroy
      redirect_to "/post/index"
    else
      # redirect_to "/home/index"
      redirect_to "/post/index"
    end
    
  end

  def show
    @post = Post.find(params[:id])
    # Post.find_by_title # 제목으로 검색이 가능
  end
  
  def search
    # Post.where(:title => "밖에 비온다") # 정확하게 같은 문자열만 보여줌
    # Post.where("title LIKE ?", "%밖에 비온다%") # 문자열 앞뒤가 달라도 보여줌(%가 앞뒤로 있기 때문)
    if params[:cate] == "1"
      @post = Post.where("title LIKE ?", "%#{params[:q]}%") # Post 안에 있는 colum 중 하나를 적고 q의 값을 원한다
    elsif params[:cate] == "2"
      @post = Post.where("content LIKE ?", "%#{params[:q]}%")
    elsif params[:cate] == "3"
      @post = Post.where("title  LIKE ? OR content LIKE ?", "%#{params[:q]}%", "%#{params[:q]}%")
    elsif params[:cate] == "4"
      # @post = User.where("username LIKE ?", "%#{params[:q]}%") # 유저만 가져오기 때문에 오류가 뜬다
      @post = User.where("username LIKE ?", "%#{params[:q]}%").take.posts # take로 하나의 유저만 뽑고 그 유저는 포스트를 많이 가지고 있기 때문에 posts를 사용
    end
    
  end
  
  def ajaxCall
    count = params[:count].to_i
    @item = Post.all.at(count) # 모든 post의 해당하는 번지의 것(4번째)을 가져온다
    @return_val = {"id" => @item.id, "user" => @item.user_id, "title" => @item.title, "time" => @item.created_at}
    render json: @return_val # json으로 다시 값을 되돌려줌
  end
end

app/controllers/reply_controller.rb
class ReplyController < ApplicationController
  def create
    @reply = Reply.new
    @reply.content = params[:content]
    @reply.post_id = params[:post_id]
    @reply.user_id = current_user.id
    @reply.save
    
    redirect_to :back
  end

  def destroy
    @reply = Reply.find(params[:id])
    
    if current_user.id == @reply.user_id
      @reply.destroy
      redirect_to :back
    else
      redirect_to "/post/index"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/reply_helper.rb
module ReplyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</head>

<body>

<%= yield %>

</body>
</html>

app/views/post/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    
    <!--로그인, 로그아웃-->
    <% if user_signed_in? %>
        <div><%= current_user.email %></div>
        <a href="/users/sign_out">로그아웃</a>
    <% else %>
        <a href="/users/sign_in">로그인</a>
    <% end %>
    
    <!--검색할 수 있게 한다-->
    <form class="form-inline my-2 my-lg-0" action="/post/search" method="get">
        <div class="form-group">
          <select name="cate" class="form-control" id="exampleFormControlSelect1">
            <option value="1">제목</option>
            <option value="2">내용</option>
            <option value="3">제목+내용</option>
            <option value="4">작성자</option>
          </select>
        </div>
      <input name="q" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/post/create.html.erb
<h1>Post#create</h1>
<p>Find me in app/views/post/create.html.erb</p>

app/views/post/destroy.html.erb
<h1>Post#destroy</h1>
<p>Find me in app/views/post/destroy.html.erb</p>

app/views/post/edit.html.erb
<div class="container">
  <form action="/post/update/<%= @post.id %>" method="post">
    
    <div class="form-group">
      <label for="exampleFormControlInput1">제목</label>
      <input name="input_title" value="<%= @post.title %>" type="text" class="form-control" id="exampleFormControlInput1" placeholder="제목을 입력하세요">
    </div>
    
    <div class="form-group">
      <label for="exampleFormControlTextarea1">내용</label>
      <textarea name = "input_content" class="form-control" id="exampleFormControlTextarea1" rows="15" placeholder="내용을 입력하세요"><%= @post.content %></textarea>
    </div>
    
    <button type="submit" class="btn btn-outline-dark">수정</button>
    
  </form>
</div>

app/views/post/index.html.erb
<%= render "navbar" %> <br>
<!--다른 폴더에 있으면 /post/navbar로 경로 지정할 것-->
<div class="container">
    <table class="table">
      
      <thead class="thead-dark"> 
        <tr>
          <th scope="col">#</th>
          <th scope="col">제목</th>
          <th scope="col">작성자</th>
          <th scope="col">작성시간</th>
        </tr>
      </thead>
      
      <tbody>
        <% @post.each do |p| %>
            <tr>
              <th scope="row"><%= p.id %></th>
              <td><a href="/post/show/<#%= p.id %>"><%= p.title %></a></td>
              <td><%= p.user.username%></td>
              <td><%= p.created_at.to_s.split("+").first %></td>
            </tr>
        <% end %>
      </tbody>

    </table>
    
    <div style="text-align:right;"><a href="/post/new"><button type="button" class="btn btn-outline-dark">글쓰기</button></a></div>



  <% @post.each do |p| %>
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="https://s-i.huffpost.com/gen/5177890/thumbs/o-APPLE-570.jpg?3" alt="Card image cap">
      <div class="card-body">
        <h5 class="card-title"><a href="/post/show/<#%= p.id %>"><%= p.title %></h5>
        <p class="card-text"><%= p.id %></p>
        <a href="#" class="btn btn-primary"><%= p.user.username%></a>
        <div><%= p.created_at.to_s.split("+").first %></div>
      </div>
    </div>
  <% end %>

<div id="enters"></div>

</div>



<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>

<script>

  var count = 4; // 처음에 네장만 보여주고 스크롤 할 때 한장씩 추가해서 보여준다.
  var stringTemp = "";
  
  function call(){ // call을 언제 콜하는가? 아래쪽에 닿았을 때
    $.ajax({ // post ajaxCall로 던저서 4가 ajaxcall의 count가 받는다
        type:"get",
        url:"/post/ajaxCall", // post controller의 ajaxCall을 정의해준다
        data : {'count' : count}, // count를 count로 넘기는거
        dataType : "json",
        success: function(data){
            alert(data["title"]); // title이 넘어옴 
        },
        error: function(error) {
            alert(error);
        }  
    });

  }
  
  
  var page = 1; 
  
  
$(window).scroll(function() {
    if ($(document).height() > $(window).height()) {
      //console.log(++page);
      //$("#enters").append("<h1>Page " + page);
      call();
      
    }
});
</script>




<!--<button onclick = "hi_1()">hi</button>-->
<!--<button onclick = "hi_2('꺄', '꾜')">hihi</button>-->
<!--<br></br>-->


<!--<input id = "idv_1"></input>-->
<!--<button onclick = "add_1()"> + </button>-->
<!--<input id = "idv_2"></input>-->
<!--=-->
<!--<input id = "idr_1"></input>-->
<!--<br></br>-->


<!--<span>1</span>-->
<!--<button onclick = "add_2(<#%= 1 %>,<%#= 2 %>)">+</button>-->
<!--<span>2</span>-->
<!--=-->
<!--<input id = "idr_2"></input>-->


<!--<script>-->
<!--  function add_2(_val1, _val2){-->
<!--    document.getElementById("idr_2").value = (_val1 + _val2);-->
<!--  }-->
  <!--function add_1(){ // id를 통해 값을 찾아서 반환할 수 있다-->
<!--    var A = document.getElementById("idv_1").value;-->
<!--    var B = document.getElementById("idv_2").value;-->
<!--    var C = Number(A) + Number(B);-->
<!--    alert(C);-->
<!--    document.getElementById("idr_1").value = C;-->
<!--  }-->
  
  
<!--  function hi_1(){-->
    <!--var A = "hi"; // 변수, 자료형 상관 없음-->
<!--    var B = 123123 + "a"-->
    
<!--  }-->
  
  <!--function hi_2(_value, apple){ // 아무 이름이나 쓴다-->
<!--    alert(_value + " HI! " + apple);-->
<!--  }-->
<!--</script>-->

app/views/post/new.html.erb
<div class="container">
  <form action="/post/create" method="post" enctype="multipart/form-data"> <!-- create로 new 화면의 내용을 나른다 사진전송하기 위해 enctype 필요-->
    
    <div class="form-group">
      <label for="exampleFormControlInput1">제목</label>
      <input name="input_title" type="text" class="form-control" id="exampleFormControlInput1" placeholder="제목을 입력하세요">
    </div>
    
    <div class="form-group">
      <label for="exampleFormControlTextarea1">내용</label>
      <textarea name = "input_content" class="form-control" id="exampleFormControlTextarea1" rows="15" placeholder="내용을 입력하세요"></textarea>
    </div>
    
    <input name="image" type="file" accept="image/*"></input> <!--올릴 수 있는 파일 제한-->
    
    <button type="submit" class="btn btn-outline-dark">작성</button>
    
  </form>
</div>

app/views/post/search.html.erb
<%= render "navbar" %> <br>
<!--다른 폴더에 있으면 /post/navbar로 경로 지정할 것-->
<div class="container">
    <table class="table">
      
      <thead class="thead-dark"> 
        <tr>
          <th scope="col">#</th>
          <th scope="col">제목</th>
          <th scope="col">작성자</th>
          <th scope="col">작성시간</th>
        </tr>
      </thead>
      
      <tbody>
        <% @post.each do |p| %>
            <tr>
              <th scope="row"><%= p.id %></th>
              <td><a href="/post/show/<%= p.id %>"><%= p.title %></a></td>
              <td><%= p.user.username%></td>
              <td><%= p.created_at.to_s.split("+").first %></td>
            </tr>
        <% end %>
      </tbody>

    </table>
    
    <div style="text-align:right;"><a href="/post/new"><button type="button" class="btn btn-outline-dark">글쓰기</button></a></div>

</div>

app/views/post/show.html.erb
<div class="container">
    
    <h1><%= @post.title %></h1><hr />
    
    <div style="text-align:right;">
        <div><%= @post.created_at.to_s.split("+").first %> (<%= time_ago_in_words(@post.created_at) %> ago)</div>
        <div><%= @post.user.username %></div>
        <a href="/post/edit/<%= @post.id %>"><span class="badge badge-light">수정</span></a>
        <a href="/post/destroy/<%= @post.id %>"><span class="badge badge-dark">삭제</span></a>
    </div>
    <hr>
    
    <!-- size = count = length-->
    <div><%= @post.liked_users.size %>명이 좋아합니다.</div>
    <% if current_user.is_like?(@post) %>
        <a href="/likes/likes_toggle/<%= @post.id %>">좋아요 취소</a>
        <!--%= link_to "좋아요", likes_likes_toggle_path(@post), method="post" %>-->
    <% else %>
        <a href="/likes/likes_toggle/<%= @post.id %>">좋아요</a>
    <% end %>
    
    
    <p><%= simple_format(@post.content) %></p>
    
    <% unless @post.image.nil? %>
        <%= image_tag @post.image %>
        <%= image_tag @post.thumb %> <!--파일자체의 크기가 줄어듦-->
        <%= image_tag @post.middle %>
    <% end %> <!--db->migrate에 default를 적든 이걸 적든 함. ""과 nil은 다르기 때문 -->
    <hr></hr>
    
    <div style="text-align:right;"><a href="/post/index"><button type="button" class="btn btn-outline-dark">목록</button></a></div>
    <br>
    
    <% @post.replies.each do |r| %> <!-- post의 모든 replies를 하나씩 r(reply model)로 뽑음: 1-n관계 -->
        <%= r.user.username %>: <%= r.content %>
        <a href="/reply/destroy/<%= r.id %>"><span class="badge badge-warning">삭제</span></a>
        <br>
    <% end %>
    <br>
    
    <form action="/reply/create" method="post">
        <input name="post_id" value="<%= @post.id %>" hidden="true"></input>
        <div class="row">
            <textarea name="content" class="form-control col-11" id="exampleFormControlTextarea1" rows="3"></textarea>
            <button type="submit" class="btn btn-outline-dark col-1">작성</button>
        </div>
    </form>
    
</div>

app/views/post/update.html.erb
<h1>Post#update</h1>
<p>Find me in app/views/post/update.html.erb</p>

app/views/reply/create.html.erb
<h1>Reply#create</h1>
<p>Find me in app/views/reply/create.html.erb</p>

app/views/reply/destroy.html.erb
<h1>Reply#destroy</h1>
<p>Find me in app/views/reply/destroy.html.erb</p>